section .text				;
	global strncmp:function		;

strncmp:				;
	mov	rcx, -1			;
	cmp	rdx, 0h			;
	jle	strncmp_special		;
	cmp	rdi, 0h			;
	je	strncmp_null_1		;
	cmp	rsi, 0h			;
	je	strncmp_null_2		;
strncmp_begin:				;
	inc	rcx			;
	cmp	rcx, rdx		;
	je	strncmp_last		;
	cmp	byte[rdi + rcx], 0h	;
	je	strncmp_return		;
	cmp	byte[rsi + rcx], 0h	;
	je	strncmp_return		;
	mov	al, byte[rdi + rcx]	;
	cmp	al, byte[rsi + rcx]	;
	jne	strncmp_return		;
	jmp	strncmp_begin		;
strncmp_last:				;
	sub	rcx, 1			;
strncmp_return:				;
	movsx	eax, byte[rdi + rcx]	;
	movsx	edx, byte[rsi + rcx]	;
	sub	eax, edx		;
	ret				;
strncmp_special:			;
	mov	eax, 0			;
	ret				;
strncmp_null_1:				;
	cmp	rsi, 0h			;
	je	strncmp_special		;
	mov	eax, 0h			;
	movsx	edx, byte[rsi]		;
	sub	eax, edx		;
	ret				;
strncmp_null_2:				;
	movsx	eax, byte[rdi]		;
	ret				;
