section .text				;
	global strpbrk:function		;

strpbrk:				;
	mov	rcx, -1			;
	mov	r10, rdi		;
	cmp	rdi, 0h			;
	je	strpbrk_null		;
	mov	r11, rsi		;
	cmp	rsi, 0h			;
	je	strpbrk_null		;
strpbrk_begin:				;
	inc	rcx			;
	cmp	byte[r10 + rcx], 0h	;
	je	strpbrk_null		;
	mov	r12, -1			;
strpbrk_intern:				;
	inc	r12			;
	cmp	byte[r11 + r12], 0h	;
	je	strpbrk_begin		;
	mov	al, byte[r11 + r12]	;
	cmp	al, byte[r10 + rcx]	;
	je	strpbrk_end		;
	jmp	strpbrk_intern		;
strpbrk_end:				;
	lea	eax, [r10 + rcx]	;
	ret				;
strpbrk_null:				;
	mov	eax, 0h			;
	ret				;
