/*
** call_handler.c for call_handler.c in /home/nicolas.trognot/rendu/Instrumentation/PSU_2016_ftrace/srcs
**
** Made by Nicolas TROGNOT
** Login   <nicolas.trognot@epitech.net>
**
** Started on  Sat May  6 14:20:57 2017 Nicolas TROGNOT
** Last update Sun May  7 22:44:24 2017 Alexis Papadimitriou
*/

#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <sys/ptrace.h>
#include "ftrace.h"

static const t_sysmap g_syscallmap[329] =
  {
    {"read", THREE_ARGS},
    {"write", THREE_ARGS},
    {"open", TWO_ARGS},
    {"close", ONE_ARG},
    {"stat", TWO_ARGS},
    {"fstat", TWO_ARGS},
    {"lstat", TWO_ARGS},
    {"poll", THREE_ARGS},
    {"lseek", THREE_ARGS},
    {"mmap", SIX_ARGS},
    {"mprotect", THREE_ARGS},
    {"munmap", TWO_ARGS},
    {"brk", ONE_ARG},
    {"rt_sigaction", THREE_ARGS},
    {"rt_sigprocmask", THREE_ARGS},
    {"rt_sigreturn", ONE_ARG},
    {"ioctl", THREE_ARGS},
    {"pread64", FOUR_ARGS},
    {"pwrite64", FOUR_ARGS},
    {"readv", THREE_ARGS},
    {"writev", THREE_ARGS},
    {"access", TWO_ARGS},
    {"pipe", ONE_ARG},
    {"select", FIVE_ARGS},
    {"sched_yield", NO_ARG},
    {"mremap", FOUR_ARGS},
    {"msync", THREE_ARGS},
    {"mincore", THREE_ARGS},
    {"madvise", THREE_ARGS},
    {"shmget", THREE_ARGS},
    {"shmat", THREE_ARGS},
    {"shmctl", THREE_ARGS},
    {"dup", ONE_ARG},
    {"dup2", TWO_ARGS},
    {"pause", NO_ARG},
    {"nanosleep", TWO_ARGS},
    {"getitimer", TWO_ARGS},
    {"alarm", ONE_ARG},
    {"setitimer", THREE_ARGS},
    {"getpid", NO_ARG},
    {"sendfile", FOUR_ARGS},
    {"socket", THREE_ARGS},
    {"connect", THREE_ARGS},
    {"accept", THREE_ARGS},
    {"sendto", SIX_ARGS},
    {"recvfrom", SIX_ARGS},
    {"sendmsg", THREE_ARGS},
    {"recvmsg", THREE_ARGS},
    {"shutdown", TWO_ARGS},
    {"bind", THREE_ARGS},
    {"listen", TWO_ARGS},
    {"getsockname", THREE_ARGS},
    {"getpeername", THREE_ARGS},
    {"socketpair", FOUR_ARGS},
    {"setsockopt", FIVE_ARGS},
    {"getsockopt", FIVE_ARGS},
    {"clone", FIVE_ARGS},
    {"fork", NO_ARG},
    {"vfork", NO_ARG},
    {"execve", THREE_ARGS},
    {"exit", ONE_ARG},
    {"wait4", FOUR_ARGS},
    {"kill", TWO_ARGS},
    {"uname", ONE_ARG},
    {"semget", THREE_ARGS},
    {"semop", THREE_ARGS},
    {"semctl", THREE_ARGS},
    {"shmdt", ONE_ARG},
    {"msgget", TWO_ARGS},
    {"msgsnd", FOUR_ARGS},
    {"msgrcv", FIVE_ARGS},
    {"msgctl", THREE_ARGS},
    {"fcntl", TWO_ARGS},
    {"flock", TWO_ARGS},
    {"fsync", ONE_ARG},
    {"fdatasync", ONE_ARG},
    {"truncate", TWO_ARGS},
    {"ftruncate", TWO_ARGS},
    {"getdents", THREE_ARGS},
    {"getcwd", TWO_ARGS},
    {"chdir", ONE_ARG},
    {"fchdir", ONE_ARG},
    {"rename", TWO_ARGS},
    {"mkdir", TWO_ARGS},
    {"rmdir", ONE_ARG},
    {"creat", TWO_ARGS},
    {"link", TWO_ARGS},
    {"unlink", ONE_ARG},
    {"symlink", TWO_ARGS},
    {"readlink", THREE_ARGS},
    {"chmod", TWO_ARGS},
    {"fchmod", TWO_ARGS},
    {"chown", THREE_ARGS},
    {"fchown", THREE_ARGS},
    {"lchown", THREE_ARGS},
    {"umask", ONE_ARG},
    {"gettimeofday", TWO_ARGS},
    {"getrlimit", TWO_ARGS},
    {"getrusage", TWO_ARGS},
    {"sysinfo", ONE_ARG},
    {"times", ONE_ARG},
    {"ptrace", FOUR_ARGS},
    {"getuid", NO_ARG},
    {"syslog", THREE_ARGS},
    {"getgid", NO_ARG},
    {"setuid", ONE_ARG},
    {"setgid", ONE_ARG},
    {"geteuid", NO_ARG},
    {"getegid", NO_ARG},
    {"setpgid", TWO_ARGS},
    {"getppid", NO_ARG},
    {"getpgrp", ONE_ARG},
    {"setsid", NO_ARG},
    {"setreuid", TWO_ARGS},
    {"setregid", TWO_ARGS},
    {"getgroups", TWO_ARGS},
    {"setgroups", TWO_ARGS},
    {"setresuid", THREE_ARGS},
    {"getresuid", THREE_ARGS},
    {"setresgid", THREE_ARGS},
    {"getresgid", THREE_ARGS},
    {"getpgid", ONE_ARG},
    {"setfsuid", ONE_ARG},
    {"setfsgid", ONE_ARG},
    {"getsid", ONE_ARG},
    {"capget", TWO_ARGS},
    {"capset", TWO_ARGS},
    {"rt_sigpending", ONE_ARG},
    {"rt_sigtimedwait", THREE_ARGS},
    {"rt_sigqueueinfo", THREE_ARGS},
    {"rt_sigsuspend", ONE_ARG},
    {"sigaltstack", TWO_ARGS},
    {"utime", TWO_ARGS},
    {"mknod", THREE_ARGS},
    {"uselib", ONE_ARG},
    {"personality", ONE_ARG},
    {"ustat", TWO_ARGS},
    {"statfs", TWO_ARGS},
    {"fstatfs", TWO_ARGS},
    {"sysfs", TWO_ARGS},
    {"getpriority", TWO_ARGS},
    {"setpriority", THREE_ARGS},
    {"sched_setparam", TWO_ARGS},
    {"sched_getparam", TWO_ARGS},
    {"sched_setscheduler", THREE_ARGS},
    {"sched_getscheduler", ONE_ARG},
    {"sched_get_priority_max", ONE_ARG},
    {"sched_get_priority_min", ONE_ARG},
    {"sched_rr_get_interval", TWO_ARGS},
    {"mlock", TWO_ARGS},
    {"munlock", TWO_ARGS},
    {"mlockall", ONE_ARG},
    {"munlockall", NO_ARG},
    {"vhangup", NO_ARG},
    {"modify_ldt", THREE_ARGS},
    {"pivot_root", TWO_ARGS},
    {"_sysctl", ONE_ARG},
    {"prctl", FIVE_ARGS},
    {"arch_prctl", TWO_ARGS},
    {"adjtimex", ONE_ARG},
    {"setrlimit", TWO_ARGS},
    {"chroot", ONE_ARG},
    {"sync", ONE_ARG},
    {"acct", ONE_ARG},
    {"settimeofday", TWO_ARGS},
    {"mount", FIVE_ARGS},
    {"umount2", TWO_ARGS},
    {"swapon", TWO_ARGS},
    {"swapoff", ONE_ARG},
    {"reboot", FOUR_ARGS},
    {"sethostname", TWO_ARGS},
    {"setdomainname", TWO_ARGS},
    {"iopl", ONE_ARG},
    {"ioperm", THREE_ARGS},
    {"create_module", TWO_ARGS},
    {"init_module", THREE_ARGS},
    {"delete_module", TWO_ARGS},
    {"get_kernel_syms", ONE_ARG},
    {"query_module", FIVE_ARGS},
    {"quotactl", FOUR_ARGS},
    {"nfsservctl", THREE_ARGS},
    {"getpmsg", FIVE_ARGS},
    {"putpmsg", FIVE_ARGS},
    {"afs_syscall", NO_ARG},
    {"tuxcall", NO_ARG},
    {"security", NO_ARG},
    {"gettid", NO_ARG},
    {"readahead", THREE_ARGS},
    {"setxattr", FIVE_ARGS},
    {"lsetxattr", FIVE_ARGS},
    {"fsetxattr", FIVE_ARGS},
    {"getxattr", FOUR_ARGS},
    {"lgetxattr", FOUR_ARGS},
    {"fgetxattr", FOUR_ARGS},
    {"listxattr", THREE_ARGS},
    {"llistxattr", THREE_ARGS},
    {"flistxattr", THREE_ARGS},
    {"removexattr", TWO_ARGS},
    {"lremovexattr", TWO_ARGS},
    {"fremovexattr", TWO_ARGS},
    {"tkill", TWO_ARGS},
    {"time", ONE_ARG},
    {"futex", SIX_ARGS},
    {"sched_setaffinity", THREE_ARGS},
    {"sched_getaffinity", THREE_ARGS},
    {"set_thread_area", ONE_ARG},
    {"io_setup", TWO_ARGS},
    {"io_destroy", ONE_ARG},
    {"io_getevents", FIVE_ARGS},
    {"io_submit", THREE_ARGS},
    {"io_cancel", THREE_ARGS},
    {"get_thread_area", ONE_ARG},
    {"lookup_dcookie", THREE_ARGS},
    {"epoll_create", ONE_ARG},
    {"epoll_ctl_old", NO_ARG},
    {"epoll_wait_old", NO_ARG},
    {"remap_file_pages", FIVE_ARGS},
    {"getdents64", THREE_ARGS},
    {"set_tid_address", ONE_ARG},
    {"restart_syscall", NO_ARG},
    {"semtimedop", FOUR_ARGS},
    {"fadvise64", FOUR_ARGS},
    {"timer_create", THREE_ARGS},
    {"timer_settime", FOUR_ARGS},
    {"timer_gettime", TWO_ARGS},
    {"timer_getoverrun", ONE_ARG},
    {"timer_delete", ONE_ARG},
    {"clock_settime", TWO_ARGS},
    {"clock_gettime", TWO_ARGS},
    {"clock_getres", TWO_ARGS},
    {"clock_nanosleep", FOUR_ARGS},
    {"exit_group", ONE_ARG},
    {"epoll_wait", FOUR_ARGS},
    {"epoll_ctl", FOUR_ARGS},
    {"tgkill", THREE_ARGS},
    {"utimes", TWO_ARGS},
    {"vserver", NO_ARG},
    {"mbind", SIX_ARGS},
    {"set_mempolicy", THREE_ARGS},
    {"get_mempolicy", FIVE_ARGS},
    {"mq_open", TWO_ARGS},
    {"mq_unlink", ONE_ARG},
    {"mq_timedsend", FIVE_ARGS},
    {"mq_timedreceive", FIVE_ARGS},
    {"mq_notify", TWO_ARGS},
    {"mq_getsetattr", THREE_ARGS},
    {"kexec_load", THREE_ARGS},
    {"waitid", FOUR_ARGS},
    {"add_key", FIVE_ARGS},
    {"request_key", FOUR_ARGS},
    {"keyctl", ONE_ARG},
    {"ioprio_set", THREE_ARGS},
    {"ioprio_get", TWO_ARGS},
    {"inotify_init", NO_ARG},
    {"inotify_add_watch", THREE_ARGS},
    {"inotify_rm_watch", TWO_ARGS},
    {"migrate_pages", FOUR_ARGS},
    {"openat", THREE_ARGS},
    {"mkdirat", THREE_ARGS},
    {"mknodat", FOUR_ARGS},
    {"fchownat", FIVE_ARGS},
    {"futimesat", THREE_ARGS},
    {"newfstatat", TWO_ARGS},
    {"unlinkat", THREE_ARGS},
    {"renameat", FOUR_ARGS},
    {"linkat", FIVE_ARGS},
    {"symlinkat", THREE_ARGS},
    {"readlinkat", FOUR_ARGS},
    {"fchmodat", FOUR_ARGS},
    {"faccessat", FOUR_ARGS},
    {"pselect6", FIVE_ARGS},
    {"ppoll", FOUR_ARGS},
    {"unshare", ONE_ARG},
    {"set_robust_list", TWO_ARGS},
    {"get_robust_list", THREE_ARGS},
    {"splice", SIX_ARGS},
    {"tee", FOUR_ARGS},
    {"sync_file_range", FOUR_ARGS},
    {"vmsplice", FOUR_ARGS},
    {"move_pages", FIVE_ARGS},
    {"utimensat", FOUR_ARGS},
    {"epoll_pwait", FIVE_ARGS},
    {"signalfd", THREE_ARGS},
    {"timerfd_create", TWO_ARGS},
    {"eventfd", TWO_ARGS},
    {"fallocate", FOUR_ARGS},
    {"timerfd_settime", FOUR_ARGS},
    {"timerfd_gettime", TWO_ARGS},
    {"accept4", FOUR_ARGS},
    {"signalfd4", THREE_ARGS},
    {"eventfd2", TWO_ARGS},
    {"epoll_create1", ONE_ARG},
    {"dup3", THREE_ARGS},
    {"pipe2", TWO_ARGS},
    {"inotify_init1", ONE_ARG},
    {"preadv", FOUR_ARGS},
    {"pwritev", THREE_ARGS},
    {"rt_tgsigqueueinfo", FOUR_ARGS},
    {"perf_event_open", FIVE_ARGS},
    {"recvmmsg", FIVE_ARGS},
    {"fanotify_init", TWO_ARGS},
    {"fanotify_mark", FIVE_ARGS},
    {"prlimit64", THREE_ARGS},
    {"name_to_handle_at", FIVE_ARGS},
    {"open_by_handle_at", THREE_ARGS},
    {"clock_adjtime", NO_ARG},
    {"syncfs", ONE_ARG},
    {"sendmmsg", FOUR_ARGS},
    {"setns", TWO_ARGS},
    {"getcpu", THREE_ARGS},
    {"process_vm_readv", SIX_ARGS},
    {"process_vm_writev", SIX_ARGS},
    {"kcmp", FIVE_ARGS},
    {"finit_module", THREE_ARGS},
    {"sched_setattr", THREE_ARGS},
    {"sched_getattr", FOUR_ARGS},
    {"renameat2", FIVE_ARGS},
    {"seccomp", THREE_ARGS},
    {"getrandom", THREE_ARGS},
    {"memfd_create", TWO_ARGS},
    {"kexec_file_load", FIVE_ARGS},
    {"bpf", THREE_ARGS},
    {"execveat", FIVE_ARGS},
    {"userfaultfd", ONE_ARG},
    {"membarrier", TWO_ARGS},
    {"mlock2", THREE_ARGS},
    {"copy_file_range", SIX_ARGS},
    {"preadv2", FOUR_ARGS},
    {"pwritev2", FOUR_ARGS}
  };

void	syscall_prompt(long call, struct user_regs_struct regs)
{
  dprintf(1, "Syscall %s", g_syscallmap[call].sysname);
  dprintf(1, g_syscallmap[call].arg_format, regs.rdi, regs.rsi,
	  regs.rdx, regs.rcx, regs.r10, regs.r8, regs.r9);
}

int		is_a_syscall(struct user_regs_struct regs, pid_t pid)
{
  t_call        call;

  call.val = ptrace(PTRACE_PEEKDATA, pid, regs.rip, 0);
  if ((call.addr[0] == 0xCD && call.addr[1] == 0x80) ||
      (call.addr[0] == 0x0F && call.addr[1] == 0x05))
    return (1);
  return (0);
}

int		is_a_ret(struct user_regs_struct regs, pid_t pid)
{
  t_call	call;

  call.val = ptrace(PTRACE_PEEKDATA, pid, regs.rip, 0);
  if (call.addr[0] == 0xc3)
    return (1);
  return (0);
}

long		is_a_relative_call(struct user_regs_struct regs,
				   pid_t pid)
{
  t_call	call;

  call.val = ptrace(PTRACE_PEEKDATA, pid, regs.rip, 0);
  if (call.addr[0] == 0xe8 || call.addr[0] == 0xff)
    return (1);
  return (-1);
}
