section .text				;
	global atoi:function		;

atoi:					;
	mov	eax, 0			;
	mov	r10, 1			;
	cmp	rdi, 0h			;
	je	atoi_end		;
atoi_begin:				;
	cmp	byte[rdi], 0h		;
	je	atoi_value		;
	cmp	byte[rdi], '0'		;
	jl	atoi_minus		;
	cmp	byte[rdi], '9'		;
	jg	atoi_minus		;
	jmp	atoi_sum		;
atoi_minus:				;
	cmp	byte[rdi], '-'		;
	jne	atoi_value		;
	cmp	r10, -1			;
	je	atoi_have_value		;
	jmp	atoi_neg		;
atoi_have_no_value:			;
	je	atoi_end		;
atoi_have_value:			;
	cmp	eax, 0			;
	je	atoi_have_no_value	;
	jmp	atoi_value		;
atoi_neg:				;
	neg	r10			;
	inc	rdi			;
	jmp	atoi_begin		;
atoi_sum:				;
	imul	eax, 10			;
	movzx	r11, byte[rdi]		;
	sub	r11b, '0'		; 0x30
	add	eax, r11d		;
	inc	rdi			;
	jmp	atoi_begin		;
atoi_value:				;
	imul	eax, r10d		;
atoi_end:				;
	ret				;
