section .text				;
	global atol:function		;

atol:					;
	mov	rax, 0			;
	mov	r10, 1			;
	cmp	rdi, 0h			;
	je	atol_end		;
atol_begin:				;
	cmp	byte[rdi], 0h		;
	je	atol_value		;
	cmp	byte[rdi], '0'		;
	jl	atol_minus		;
	cmp	byte[rdi], '9'		;
	jg	atol_minus		;
	jmp	atol_sum		;
atol_minus:				;
	cmp	byte[rdi], '-'		;
	jne	atol_value		;
	cmp	r10, -1			;
	je	atol_have_value		;
	jmp	atol_neg		;
atol_have_no_value:			;
	je	atol_end		;
atol_have_value:			;
	cmp	rax, 0			;
	je	atol_have_no_value	;
	jmp	atol_value		;
atol_neg:				;
	neg	r10			;
	inc	rdi			;
	jmp	atol_begin		;
atol_sum:				;
	imul	rax, 10			;
	movzx	r11, byte[rdi]		;
	sub	r11b, '0'		; 0x30
	add	rax, r11		;
	inc	rdi			;
	jmp	atol_begin		;
atol_value:				;
	imul	rax, r10		;
atol_end:				;
	ret				;
